### PR TITLE
[Feature Request] Move script file to CRUD for cross-theme use

### PR DESCRIPTION
**Pull request by maurohmartinez**
Everything [here](https://github.com/Laravel-Backpack/CRUD/issues/5057).

### CODE REVIEW

**Comment by tabacitu** [comment]
Awesome! Thanks @maurohmartinez . Heads-up, I've moved the general `scripts` and `styles` files from `resources/views/crud/inc` to `resources/views/ui/inc`. I think it makes more sense there because:
- the files aren't really CRUD-specific, they're about the UI;
- that way each file can individually override that file, if needed;

**Comment by maurohmartinez** [comment]
@tabacitu great! Anything else from needed here? Just making sure.

**Comment by tabacitu** [comment]
Nope, all good from my perspective. The only changes needed in order to merge all of these are in https://github.com/Laravel-Backpack/CRUD/pull/5075

**Review by tabacitu — APPROVED** [review]

**Comment by maurohmartinez** [comment]
> Nope, all good from my perspective. The only changes needed in order to merge all of these are in [Laravel-Backpack/CRUD#5075](https://github.com/Laravel-Backpack/CRUD/pull/5075)

@tabacitu I think I made all changes, should be fine by now :)

**Pull request merged**
